# Generated by Django 4.1.3 on 2022-11-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_size_tag_primarycategory_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tag Master',
                'verbose_name_plural': 'Tags Master',
                'db_table': 'tag_master',
            },
        ),
    ]
