# Generated by Django 4.1.3 on 2023-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size_mapping'),
        ),
    ]
