# Generated by Django 4.1.3 on 2022-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_primary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_name',
            field=models.SlugField(default='hello-world', max_length=60),
            preserve_default=False,
        ),
    ]
