# Generated by Django 4.1.3 on 2022-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_name',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
