# Generated by Django 4.1.3 on 2022-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Product description goes here', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(default='Product details are presented here', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.CharField(default='Highlight 1; Highlight 2; Highlight 3; Highlight 4', help_text='Separate each list item with a semicolon (;)', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=9999.99, max_digits=7),
            preserve_default=False,
        ),
    ]
