# Generated by Django 4.1.3 on 2022-12-14 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 17, 50, 19, 104898, tzinfo=datetime.timezone.utc), verbose_name='OTP Expires on'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userotp',
            name='mobile',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(max_length=256, verbose_name='OTP'),
        ),
    ]
