# Generated by Django 4.1.3 on 2023-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(db_index=True, error_messages={'unique': 'User already exists. Please use a different mobile number'}, max_length=10, unique=True),
        ),
    ]
