# Generated by Django 4.1.3 on 2022-12-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userotp_expires_on_alter_userotp_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('display_name', models.CharField(max_length=64, verbose_name='Display Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['display_name'],
            },
        ),
    ]
