# Generated by Django 4.1.3 on 2023-05-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='modified_by',
        ),
    ]
