# Generated by Django 4.1.3 on 2022-12-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Attempts'),
        ),
    ]
