# Generated by Django 4.1.3 on 2022-12-15 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userotp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 7, 57, 16, 794887, tzinfo=datetime.timezone.utc), verbose_name='Last Login Time'),
            preserve_default=False,
        ),
    ]
