# Generated by Django 4.1.3 on 2023-05-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description'),
        ('cart_wishlist', '0002_cart_from_date_cart_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.size'),
            preserve_default=False,
        ),
    ]
