# Generated by Django 4.1.3 on 2023-05-06 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_wishlist', '0004_alter_cart_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Time Master',
                'verbose_name_plural': 'Time Master',
                'db_table': 'time_master',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'size'), name='unique_user_product_size_mapping', violation_error_message='Cannot add same product with same size'),
        ),
        migrations.AddField(
            model_name='timemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='timemaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='timemaster',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
    ]
