# Generated by Django 4.1.3 on 2023-05-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_wishlist', '0005_timemaster_alter_cart_from_date_alter_cart_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='deliver_at',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_deliver_at', to='cart_wishlist.timemaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='return_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_return_by', to='cart_wishlist.timemaster'),
            preserve_default=False,
        ),
    ]
